### ISSUE TITLE
Dockerize project to make development easier

### ISSUE THREAD

**Issue by VictorSNA** [locaweb/heartcheck-cas#3]
### Motivation
It's need to make easier to contribute to `heartcheck-cas`!

Dockerizing it is a good start, it'll give a consistent and isolated environment.

**DOD**

- Must use the most possible updated Ruby version;
- Must pass all tests;
- README must be updated to include the recently updates.

**Comment by m8051** [comment]
Hi @VictorSNA and @TecnoSigma, I'd like to contribute to this issue. Thanks in advance.

**Comment by m8051** [comment]
@VictorSNA , @TecnoSigma I created a PR in the attempt to address this issue, please let me know if there's anything else I can do to help or any potential change to better follow your procedures.

Thanks in advance.

**Comment by VictorSNA** [comment]
Thanks!
