### ISSUE TITLE
Use GitHub Actions instead TravisCI

### ISSUE THREAD

**Issue by VictorSNA** [locaweb/heartcheck-cas#6]
We want to replace travis CI by Github actions.

You can follow the example: https://github.com/locaweb/heartcheck/pull/51

**DoD**

- Must pass all tests in forked repo;
- Must remove travis;
- Must run only supported ruby versions.

**Comment by sdesani** [comment]
@VictorSNA , created the PR for this issue - https://github.com/locaweb/heartcheck-cas/pull/7. Can you assign this issue to me and also whenever you get a chance, if you can review and provide feedback on the PR.
